version: '2'
services:
  php-fpm:
    build: ./docker/php
    volumes:
        - .:/var/www/html
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
        - "9000:9000"
    links:
        - mysql

  nginx:
    build: ./docker/nginx
    volumes:
        - ./docker/nginx/sites:/etc/nginx/sites-available
        - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        - php-fpm

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./docker/mysql/data/db:/var/lib/mysql
volumes:
    mysql:
        driver: "local"
